# Medial Flow Tracker with video

In [2]:
import cv2
import numpy as np

In [3]:
cap=cv2.VideoCapture('D:\pyplib\imageRecon\check\video.jpg')

_,frame=cap.read()


cap.isOpened()

False

In [ ]:
bbox=cv2.selectROI(frame,False)
cv2.destroyAllWindows()
import cv2
import numpy as np

 
    # Read image
im = cv2.imread("D:\pyplib\imageRecon\check\image.jpg")
     
    # Select ROI
fromCenter = False
r = cv2.selectROI(im, fromCenter)
     
    # Crop image
imCrop = im[int(r[1]):int(r[1]+r[3]), int(r[0]):int(r[0]+r[2])]
 
    # Display cropped image
cv2.imshow("Image", imCrop)
cv2.waitKey(0)


In [3]:
im = cv2.imread("D:\pyplib\imageRecon\check\image.jpg")
print(im)[p[pp[]]]

[[[255 222 172]
  [255 222 172]
  [255 223 173]
  ..., 
  [ 31   9   3]
  [ 35  19  13]
  [ 30  18  14]]

 [[255 223 173]
  [255 223 173]
  [255 224 174]
  ..., 
  [ 30  14   7]
  [ 20  10   3]
  [ 54  45  41]]

 [[255 225 174]
  [255 225 174]
  [255 226 175]
  ..., 
  [ 37  32  23]
  [  5   6   0]
  [ 34  36  30]]

 ..., 
 [[133 131 151]
  [136 134 154]
  [110 108 128]
  ..., 
  [119 121 145]
  [115 119 143]
  [104 108 132]]

 [[126 126 150]
  [131 131 155]
  [112 110 132]
  ..., 
  [120 124 148]
  [124 128 152]
  [121 125 149]]

 [[140 141 167]
  [144 145 171]
  [139 139 163]
  ..., 
  [115 119 143]
  [113 117 141]
  [114 118 142]]]
